# Generated by Django 4.2 on 2023-04-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHead',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('main_price', models.IntegerField(null=True)),
                ('frac_price', models.IntegerField(null=True)),
                ('image', models.ImageField(default='peep-3.jpg', upload_to='')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('section_number', models.IntegerField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=1000)),
                ('course_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursehead')),
            ],
            options={
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_number', models.IntegerField()),
                ('content_name', models.CharField(max_length=200)),
                ('video_file', models.FileField(default='coursevideo.mp4', upload_to='videos/')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursesection')),
            ],
            options={
                'ordering': ['course_section', 'content_number'],
            },
        ),
    ]
